### ISSUE TITLE
Anonymizing error if there is a JSONB column in a table

### ISSUE THREAD

**Issue by koptelovav** [rheinwerk-verlag/postgresql-anonymizer#12]
I have a strange error:
```
pganonymizer.exceptions.BadDataFormat: invalid input syntax for type json
DETAIL:  Token "'" is invalid.
CONTEXT:  JSON data, line 1: {'...
COPY source, line 29, column ui_settings: "{'firstTime': True}"
```
YAML file:
```
tables:
  - accounts:
      fields:
        - name:
            provider:
              name: fake.name
        - email:
            provider:
              name: fake.email
        - phone:
            provider:
              name: fake.phone_number
        - title:
            provider:
              name: choice
              values:
                - "Mr"
                - "Mrs"
                - "Dr"
                - "Prof"
                - "Ms"

truncate:
  - django_session
```

ui_settings column values: 
`{"firstTime": true, "licenseBannerHasBeenShown": true}`
`{"firstTime": true}`
`{}`

What am I doing wrong?
